import type { ModelDefinition } from '../types.js';
import { createProviderModelCatalog, modelSupportsInputType } from './metadata.js';

const OPENAI_MODEL_DEFINITIONS = {
  'gpt-4.1': {
    rid: 'ri.language-model-service..language-model.gpt-4-1',
    modelIdentifier: 'GPT_4_1',
    displayName: 'GPT-4.1',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-05-31T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-4.1',
  },
  'gpt-4.1-mini': {
    rid: 'ri.language-model-service..language-model.gpt-4-1-mini',
    modelIdentifier: 'GPT_4_1_MINI',
    displayName: 'GPT-4.1 mini',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-05-31T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'LIGHTWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-4.1-mini',
  },
  'gpt-4.1-nano': {
    rid: 'ri.language-model-service..language-model.gpt-4-1-nano',
    modelIdentifier: 'GPT_4_1_NANO',
    displayName: 'GPT-4.1 nano',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-05-31T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'LIGHTWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-4.1-nano',
  },
  'gpt-4o': {
    rid: 'ri.language-model-service..language-model.gpt-4-o',
    modelIdentifier: 'GPT_4_O',
    displayName: 'GPT-4o',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2023-10-01T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-4o',
  },
  'gpt-5': {
    rid: 'ri.language-model-service..language-model.gpt-5',
    modelIdentifier: 'GPT_5',
    displayName: 'GPT-5',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-09-30T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5',
  },
  'gpt-5-pro': {
    rid: 'ri.language-model-service..language-model.gpt-5-pro',
    modelIdentifier: 'GPT_5_PRO',
    displayName: 'GPT-5 Pro',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-09-30T00:00:00Z',
    performance: {
      cost: 'HIGH',
      modelClass: 'REASONING',
      speed: 'LOW',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5-pro',
  },
  'gpt-5-codex': {
    rid: 'ri.language-model-service..language-model.gpt-5-codex',
    modelIdentifier: 'GPT_5_CODEX',
    displayName: 'GPT-5 Codex',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-09-29T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5-codex',
  },
  'gpt-5-mini': {
    rid: 'ri.language-model-service..language-model.gpt-5-mini',
    modelIdentifier: 'GPT_5_MINI',
    displayName: 'GPT-5 mini',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-05-30T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'LIGHTWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5-mini',
  },
  'gpt-5-nano': {
    rid: 'ri.language-model-service..language-model.gpt-5-nano',
    modelIdentifier: 'GPT_5_NANO',
    displayName: 'GPT-5 nano',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-05-30T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'LIGHTWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5-nano',
  },
  'gpt-5.1': {
    rid: 'ri.language-model-service..language-model.gpt-5-1',
    modelIdentifier: 'GPT_5_1',
    displayName: 'GPT-5.1',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-09-30T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.1',
  },
  'gpt-5.1-codex': {
    rid: 'ri.language-model-service..language-model.gpt-5-1-codex',
    modelIdentifier: 'GPT_5_1_CODEX',
    displayName: 'GPT-5.1 Codex',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-09-30T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.1-codex',
  },
  'gpt-5.1-codex-mini': {
    rid: 'ri.language-model-service..language-model.gpt-5-1-codex-mini',
    modelIdentifier: 'GPT_5_1_CODEX_MINI',
    displayName: 'GPT-5.1 Codex mini',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-09-30T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'LIGHTWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.1-codex-mini',
  },
  'gpt-5.2': {
    rid: 'ri.language-model-service..language-model.gpt-5-2',
    modelIdentifier: 'GPT_5_2',
    displayName: 'GPT-5.2',
    lifecycle: 'experimental',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2025-08-31T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.2',
  },
  'gpt-5.3-codex': {
    rid: 'ri.language-model-service..language-model.gpt-5-3-codex',
    modelIdentifier: 'GPT_5_3_CODEX',
    displayName: 'GPT-5.3 Codex',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2025-08-31T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.3-codex',
  },
  'gpt-5.4': {
    rid: 'ri.language-model-service..language-model.gpt-5-4',
    modelIdentifier: 'GPT_5_4',
    displayName: 'GPT-5.4',
    lifecycle: 'experimental',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2025-08-31T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.4',
  },
  'gpt-5.5': {
    rid: 'ri.language-model-service..language-model.gpt-5-5',
    modelIdentifier: 'GPT_5_5',
    displayName: 'GPT-5.5',
    lifecycle: 'experimental',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2025-12-31T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.5',
  },
  'gpt-5.6-sol': {
    rid: 'ri.language-model-service..language-model.gpt-5-6-sol',
    modelIdentifier: 'GPT_5_6_SOL',
    displayName: 'GPT-5.6 Sol',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2026-02-16T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.6-sol',
  },
  'gpt-5.6-terra': {
    rid: 'ri.language-model-service..language-model.gpt-5-6-terra',
    modelIdentifier: 'GPT_5_6_TERRA',
    displayName: 'GPT-5.6 Terra',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2026-02-16T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.6-terra',
  },
  'gpt-5.6-luna': {
    rid: 'ri.language-model-service..language-model.gpt-5-6-luna',
    modelIdentifier: 'GPT_5_6_LUNA',
    displayName: 'GPT-5.6 Luna',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2026-02-16T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.6-luna',
  },
  'gpt-5.4-mini': {
    rid: 'ri.language-model-service..language-model.gpt-5-4-mini',
    modelIdentifier: 'GPT_5_4_MINI',
    displayName: 'GPT-5.4 mini',
    lifecycle: 'experimental',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2025-08-31T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'LIGHTWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.4-mini',
  },
  'gpt-5.4-nano': {
    rid: 'ri.language-model-service..language-model.gpt-5-4-nano',
    modelIdentifier: 'GPT_5_4_NANO',
    displayName: 'GPT-5.4 nano',
    lifecycle: 'experimental',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'GPT_CHAT_COMPLETION',
      'GPT_WITH_VISION_COMPLETION',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_REASONING',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2025-08-31T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'LIGHTWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/gpt-5.4-nano',
  },
  o3: {
    rid: 'ri.language-model-service..language-model.o-3',
    modelIdentifier: 'O_3',
    displayName: 'o3',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'OPEN_AI_REASONING',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-05-31T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'LOW',
    },
    externalUrl: 'https://platform.openai.com/docs/models/o3',
  },
  'o4-mini': {
    rid: 'ri.language-model-service..language-model.o-4-mini',
    modelIdentifier: 'O_4_MINI',
    displayName: 'o4-mini',
    lifecycle: 'ga',
    inputTypes: [
      'GENERIC_COMPLETION',
      'GENERIC_CHAT_COMPLETION',
      'OPEN_AI_REASONING',
      'GENERIC_VISION_COMPLETION',
      'OPEN_AI_RESPONSES',
    ],
    trainingCutoffDate: '2024-05-31T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://platform.openai.com/docs/models/o4-mini',
  },
} as const satisfies Record<string, ModelDefinition>;

const OPENAI_EMBEDDING_MODEL_DEFINITIONS = {
  'text-embedding-3-small': {
    rid: 'text-embedding-3-small',
    modelIdentifier: 'TEXT_EMBEDDING_3_SMALL',
    displayName: 'Text Embedding 3 Small',
    lifecycle: 'ga',
    inputTypes: ['OPEN_AI_EMBEDDINGS'],
    trainingCutoffDate: '2021-09-01T00:00:00Z',
    performance: {
      cost: 'LOW',
      modelClass: 'LIGHTWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/text-embedding-3-small',
  },
  'text-embedding-3-large': {
    rid: 'text-embedding-3-large',
    modelIdentifier: 'TEXT_EMBEDDING_3_LARGE',
    displayName: 'Text Embedding 3 Large',
    lifecycle: 'ga',
    inputTypes: ['OPEN_AI_EMBEDDINGS'],
    trainingCutoffDate: '2021-09-01T00:00:00Z',
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'HIGH',
    },
    externalUrl: 'https://platform.openai.com/docs/models/text-embedding-3-large',
  },
} as const satisfies Record<string, ModelDefinition>;

export const OPENAI_MODELS = createProviderModelCatalog('openai', OPENAI_MODEL_DEFINITIONS);
export const OPENAI_EMBEDDING_MODELS = createProviderModelCatalog(
  'openai',
  OPENAI_EMBEDDING_MODEL_DEFINITIONS,
);

export type KnownOpenAIModelId = keyof typeof OPENAI_MODELS;
export type OpenAIModelId = KnownOpenAIModelId | (string & {});
export type KnownOpenAIEmbeddingModelId = keyof typeof OPENAI_EMBEDDING_MODELS;
export type OpenAIEmbeddingModelId = KnownOpenAIEmbeddingModelId | (string & {});

export const OPENAI_MODEL_IDS = Object.freeze(
  Object.keys(OPENAI_MODELS),
) as readonly KnownOpenAIModelId[];
export const OPENAI_EMBEDDING_MODEL_IDS = Object.freeze(
  Object.keys(OPENAI_EMBEDDING_MODELS),
) as readonly KnownOpenAIEmbeddingModelId[];

const OPENAI_REASONING_MODEL_TARGETS = new Set(
  Object.entries(OPENAI_MODELS)
    .filter(([, metadata]) => modelSupportsInputType(metadata, 'OPEN_AI_REASONING'))
    .flatMap(([modelId, metadata]) => [modelId, metadata.rid]),
);

export function isKnownOpenAIReasoningTarget(modelId: string): boolean {
  return OPENAI_REASONING_MODEL_TARGETS.has(modelId);
}
