import type { ModelDefinition } from '../types.js';
import { createProviderModelCatalog } from './metadata.js';

// Metadata from Foundry enrollment; transport verified through live proxy requests.
const THIRD_PARTY_MODEL_DEFINITIONS = {
  'gemma-4-31b': {
    rid: 'ri.language-model-service..language-model.gemma-4-31b',
    modelIdentifier: 'GEMMA_4_31B',
    displayName: 'Gemma 4 31B',
    lifecycle: 'experimental',
    inputTypes: ['OPEN_AI_RESPONSES', 'GENERIC_VISION_COMPLETION'],
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://huggingface.co/google/gemma-4-31B-it',
    modelCreator: 'GOOGLE',
    transport: 'openai-responses',
  },
  'kimi-k2-5': {
    rid: 'ri.language-model-service..language-model.kimi-k2-5',
    modelIdentifier: 'KIMI_K2_5',
    displayName: 'Kimi K2.5',
    lifecycle: 'ga',
    inputTypes: ['GPT_CHAT_COMPLETION', 'GENERIC_VISION_COMPLETION'],
    performance: {
      cost: 'HIGH',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://www.kimi.com/ai-models/kimi-k2-5',
    modelCreator: 'MOONSHOT_AI',
    transport: 'openai-chat',
  },
  'kimi-k3': {
    rid: 'ri.language-model-service..language-model.kimi-k3',
    modelIdentifier: 'KIMI_K3',
    displayName: 'Kimi K3',
    lifecycle: 'experimental',
    inputTypes: ['GPT_CHAT_COMPLETION', 'GENERIC_VISION_COMPLETION', 'OPEN_AI_RESPONSES'],
    performance: {
      cost: 'HIGH',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://huggingface.co/moonshotai/Kimi-K3',
    modelCreator: 'MOONSHOT_AI',
    transport: 'openai-chat',
  },
  'llama-3-3-nemotron-super-49b-v1-5': {
    rid: 'ri.language-model-service..language-model.llama-3-3-nemotron-super-49b-v1-5',
    modelIdentifier: 'LLAMA_3_3_NEMOTRON_SUPER_49B_V1_5',
    displayName: 'Llama 3.3 Nemotron Super 49b v1.5',
    lifecycle: 'ga',
    inputTypes: [],
    performance: {
      cost: 'MEDIUM',
      modelClass: 'HEAVYWEIGHT',
      speed: 'MEDIUM',
    },
    trainingCutoffDate: '2023-12-01T00:00:00Z',
    modelCreator: 'NVIDIA',
    transport: 'unavailable',
  },
  'nemotron-3-ultra-550b-a55b-nvfp4': {
    rid: 'ri.language-model-service..language-model.nemotron-3-ultra-550b-a55b-nvfp4',
    modelIdentifier: 'NEMOTRON_3_ULTRA_550B_A55B_NVFP4',
    displayName: 'NVIDIA Nemotron 3 Ultra 550B A55B NVFP4',
    lifecycle: 'experimental',
    inputTypes: ['OPEN_AI_RESPONSES'],
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    trainingCutoffDate: '2026-05-01T00:00:00Z',
    externalUrl: 'https://build.nvidia.com/nvidia/nemotron-3-ultra-550b-a55b/modelcard',
    modelCreator: 'NVIDIA',
    transport: 'openai-responses',
  },
  'gemma-4-26b-a4b': {
    rid: 'ri.language-model-service..language-model.gemma-4-26b-a4b',
    modelIdentifier: 'GEMMA_4_26B_A4B',
    displayName: 'Gemma 4 26B A4B',
    lifecycle: 'ga',
    inputTypes: ['OPEN_AI_RESPONSES', 'GENERIC_VISION_COMPLETION'],
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    trainingCutoffDate: '2025-01-01T00:00:00Z',
    externalUrl: 'https://huggingface.co/google/gemma-4-26B-A4B-it',
    modelCreator: 'OPEN_SOURCE',
    transport: 'openai-responses',
  },
  'qwen3-235b-a22b-2507': {
    rid: 'ri.language-model-service..language-model.qwen3-235b-a22b-2507',
    modelIdentifier: 'QWEN3_235B_A22B_2507',
    displayName: 'Qwen3 235B A22B 2507',
    lifecycle: 'experimental',
    inputTypes: ['GPT_CHAT_COMPLETION'],
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://qwen.ai/blog?id=qwen3',
    modelCreator: 'QWEN',
    transport: 'openai-chat',
  },
  'qwen3-32b': {
    rid: 'ri.language-model-service..language-model.qwen3-32b',
    modelIdentifier: 'QWEN3_32B',
    displayName: 'Qwen3 32B',
    lifecycle: 'experimental',
    inputTypes: ['GPT_CHAT_COMPLETION'],
    performance: {
      cost: 'MEDIUM',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://qwen.ai/blog?id=qwen3',
    modelCreator: 'QWEN',
    transport: 'openai-chat',
  },
  'glm-5': {
    rid: 'ri.language-model-service..language-model.glm-5',
    modelIdentifier: 'GLM_5',
    displayName: 'Z.ai GLM-5',
    lifecycle: 'ga',
    inputTypes: ['GPT_CHAT_COMPLETION'],
    performance: {
      cost: 'HIGH',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://z.ai/blog/glm-5',
    modelCreator: 'Z_AI',
    transport: 'openai-chat',
  },
  'glm-5-3': {
    rid: 'ri.language-model-service..language-model.glm-5-3',
    modelIdentifier: 'GLM_5_3',
    displayName: 'Z.ai GLM-5.3',
    lifecycle: 'experimental',
    inputTypes: ['GPT_CHAT_COMPLETION', 'OPEN_AI_RESPONSES'],
    performance: {
      cost: 'HIGH',
      modelClass: 'REASONING',
      speed: 'MEDIUM',
    },
    externalUrl: 'https://huggingface.co/zai-org/GLM-5.3',
    modelCreator: 'Z_AI',
    transport: 'openai-chat',
  },
  'glm-5-3-flash': {
    rid: 'ri.language-model-service..language-model.glm-5-3-flash',
    modelIdentifier: 'GLM_5_3_FLASH',
    displayName: 'Z.ai GLM-5.3 Flash',
    lifecycle: 'experimental',
    inputTypes: ['GPT_CHAT_COMPLETION', 'GENERIC_VISION_COMPLETION', 'OPEN_AI_RESPONSES'],
    performance: {
      cost: 'LOW',
      modelClass: 'REASONING',
      speed: 'HIGH',
    },
    externalUrl: 'https://fireworks.ai/models/fireworks/glm-5p3-flash',
    modelCreator: 'Z_AI',
    transport: 'openai-chat',
  },
  'deepseek-v4-1-flash': {
    rid: 'ri.language-model-service..language-model.deepseek-v4-1-flash',
    modelIdentifier: 'DEEPSEEK_V4_1_FLASH',
    displayName: 'DeepSeek V4.1 Flash',
    lifecycle: 'experimental',
    inputTypes: ['GPT_CHAT_COMPLETION', 'GENERIC_VISION_COMPLETION', 'OPEN_AI_RESPONSES'],
    performance: {
      cost: 'LOW',
      modelClass: 'REASONING',
      speed: 'HIGH',
    },
    externalUrl: 'https://fireworks.ai/models/deepseek-ai/deepseek-v4p1-flash',
    modelCreator: 'DEEPSEEK',
    transport: 'openai-chat',
  },
} as const satisfies Record<string, ModelDefinition>;

export const THIRD_PARTY_MODELS = createProviderModelCatalog(
  'third-party',
  THIRD_PARTY_MODEL_DEFINITIONS,
);
export type KnownThirdPartyModelId = keyof typeof THIRD_PARTY_MODELS;
export type ThirdPartyModelId = KnownThirdPartyModelId | (string & {});
export const THIRD_PARTY_MODEL_IDS = Object.freeze(
  Object.keys(THIRD_PARTY_MODELS),
) as readonly KnownThirdPartyModelId[];
